### PR TITLE
Fix: Processing R help parameter

### PR DESCRIPTION
**Pull request by rldhont**
Set help parameter from the help file

Funded by Ifremer

### CODE REVIEW

**Comment by Gustry** [comment]
@rldhont The travis failure has been noticed by @JanCaha and he raised a ticket on QGIS : https://github.com/qgis/QGIS/issues/41181 We will see soon if it's fixing Travis.

But IMHO, you can keep previous version and not raise qgisMinVersion.

```python
if Qgis.QGIS_VERSION_INT >= 31600:
    param.setHelp()
```

**Comment by rldhont** [comment]
thanks @Gustry

**Comment by nyalldawson** [comment]
Looks good to me!

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
I'll push a new release after this is merged

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
